# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

name: KAI Scheduler - Upload artifacts to Google Artifact Registry
on:
  push:
    branches:
      - "main"
    tags:
      - '*.*.*'

permissions:
  contents: read
  id-token: write

env:
  DOCKER_REGISTRY: "us-central1-docker.pkg.dev/reflectionai/go-kai-scheduler"

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Extract package version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          PACKAGE_VERSION=${GITHUB_REF_NAME}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo $PACKAGE_VERSION

      - name: Extract package version from branch commit
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          PACKAGE_VERSION=0.0.0-$(git rev-parse --short HEAD)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo $PACKAGE_VERSION

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/91954828978/locations/global/workloadIdentityPools/github/providers/github-olympus-ci-cd'
          service_account: 'kai-scheduler-push@reflectionai.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build & push
        run: make build DOCKER_BUILD_PLATFORM=linux/amd64,linux/arm64 DOCKER_REPO_BASE=${{ env.DOCKER_REGISTRY }} VERSION=$PACKAGE_VERSION DOCKER_BUILDX_ADDITIONAL_ARGS=--push

      - name: Tag images as latest
        if: github.ref == 'refs/heads/main'
        run: |
          SERVICES="podgrouper scheduler binder resourcereservation snapshot-tool scalingpod nodescaleadjuster podgroupcontroller queuecontroller fairshare-simulator admission operator time-based-fairshare-simulator crd-upgrader"
          for SERVICE in $SERVICES; do
            docker buildx imagetools create \
              --tag ${{ env.DOCKER_REGISTRY }}/${SERVICE}:latest \
              ${{ env.DOCKER_REGISTRY }}/${SERVICE}:$PACKAGE_VERSION
          done

      - name: Build helm chart
        run: |
          sed -i 's#registry/local/kai-scheduler#${{ env.DOCKER_REGISTRY }}#' deployments/kai-scheduler/values.yaml
          helm package ./deployments/kai-scheduler -d ./charts --app-version $PACKAGE_VERSION --version $PACKAGE_VERSION

      - name: Push Helm Chart
        run: |
          helm push ./charts/kai-scheduler-$PACKAGE_VERSION.tgz oci://${{ env.DOCKER_REGISTRY }}
